

app:
  name: yon-online-shop
  port: ":4000"

db:
  host: localhost
  port: 5432
  name: yon_online_shop
  user: postgres
  password: postgres
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60 #second